---

sudo: required

dist: trusty

language: python

services: docker

env:
  global:
    - ANSIBLE_FORCE_COLOR: true
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '~/.ansible/roles'
  matrix:
    - DOCKER_IMAGE: 'ubuntu:16.04'
    - DOCKER_IMAGE: 'ubuntu:18.04'
    - DOCKER_IMAGE: 'centos:6'
    - DOCKER_IMAGE: 'centos/systemd:latest'

before_install:
  - python --version
  - pip --version

install:
  - ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
  - mkdir -p $ANSIBLE_ROLES_PATH
  - pip install --upgrade --requirement requirements.txt
  - git clone https://github.com/ansible/galaxy-lint-rules.git ~/galaxy-lint-rules
  - ln -s `pwd` $ANSIBLE_ROLES_PATH/$ROLE
#  - ansible-galaxy install --roles-path $ANSIBLE_ROLES_PATH --role-file ansible-role-requirements.yml

before_script:
  - docker pull $DOCKER_IMAGE
  - DOCKER_ID="$(docker run -itd --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock $DOCKER_IMAGE | head -c12)"

script:
  - yamllint -c .yamllint .
  - ansible-lint -v -r ~/galaxy-lint-rules/rules .
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --syntax-check
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff
  - tail -n 1 $ANSIBLE_LOG_PATH | grep -Eq 'changed=0 +unreachable=0 +failed=0'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
