---

dist: xenial

language: python

services: docker

env:
  matrix:
    - DOCKER_IMAGE: 'ubuntu:16.04'
    - DOCKER_IMAGE: 'ubuntu:18.04'
    - DOCKER_IMAGE: 'centos:6'
    - DOCKER_IMAGE: 'centos/systemd:latest'

before_install:
  - python --version
  - pip --version

install:
  - ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
  - mkdir -p ~/.ansible/roles
  - pip install --upgrade --requirement requirements.txt
  - git clone https://github.com/ansible/galaxy-lint-rules.git ~/.ansible/galaxy-lint-rules
  - ln -s `pwd` ~/.ansible/roles/$ROLE
#  - ansible-galaxy install --roles-path ~/.ansible/roles --role-file ansible-role-requirements.yml

script:
  - ./tests/run.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
