---

sudo: required

dist: trusty

language: python

services: docker

env:
  global:
    - ANSIBLE_FORCE_COLOR: true
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'
  matrix:
    - DOCKER_IMAGE: 'ubuntu:16.04'
    - DOCKER_IMAGE: 'ubuntu:18.04'
    - DOCKER_IMAGE: 'centos:6'
    - DOCKER_IMAGE: 'centos/systemd:latest'

before_install:
  - python --version
  - pip --version

install:
  - mkdir -p /etc/ansible/roles
  - pip install --upgrade --requirement requirements.txt
  - ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/\/ansible-role-/\//g')
  - ln -s `pwd` /etc/ansible/roles/$ROLE
#  - ansible-galaxy install -r ansible-role-requirements.yml

before_script:
  - docker pull $DOCKER_IMAGE
  - DOCKER_ID="$(docker run -itd --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock $DOCKER_IMAGE | head -c12)"

script:
  - yamllint -c .yamllint .
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --syntax-check
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff
  - ansible-playbook -i $DOCKER_ID, -c docker tests/test.yml --diff
  - tail -n 1 $ANSIBLE_LOG_PATH | grep -Eq 'changed=0 +unreachable=0 +failed=0'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
