---
dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
    roles-path: ${ANSIBLE_ROLES_PATH}
    ignore-errors: true
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ${LXC_ID}-1
    url: unix:/var/snap/lxd/common/lxd/unix.socket
    source:
      server: https://images.linuxcontainers.org
      alias: ${LXC_IMAGE}
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
